### ISSUE TITLE
[FEAT] JoinStudyView 구현

### ISSUE THREAD

**Issue by unuhqueen** [DeveloperAcademy-POSTECH/MC3-Team1-Hatnya#11]
## 💡 Issue

- 스터디 그룹 코드 입력창 만들기

## 📝  todo
- [ ] 풀스크린 모달 띄우기
- [x] 제목 라벨, 텍스트 필드 만들기
- [x] 스터디 검색 결과 컴포넌트 만들기
- [x] 코드 데이터 연동 후 데이터에 일치할 때만 검색결과 띄우기

## 참고한 코드 출처
- []()
