### ISSUE TITLE
[FEAT] NicknameView 구현

### ISSUE THREAD

**Issue by yeongwooCho** [DeveloperAcademy-POSTECH/MC3-Team1-Hatnya#12]
## 💡 Issue

<img width="284" alt="스크린샷 2022-07-19 오전 11 49 39" src="https://user-images.githubusercontent.com/48707024/179653765-fac6a86e-0454-4608-b665-8c4407a6066b.png">

## 📝  todo

- [ ] 입력과 동시에 글자 수 세서 표시해주기
- [ ] 한글자 이상 입력시에 입장 버튼 활성화
- [ ] 그룹 입장하면 입장한 사람 기존 파이어베이스의 스터디그룹에 추가하기

## 참고한 코드 출처
- []()
