### ISSUE TITLE
[FEAT] StudyListView

### ISSUE THREAD

**Issue by wonhui-kim** [DeveloperAcademy-POSTECH/MC3-Team1-Hatnya#19]
## 💡 Issue
앱 설치 시 가장 처음 보이는 화면인 StudyListView를 구현할 예정입니다.

## 📝  todo
- [x] Table View 생성
- [x] Custom Cell 생성
- [x] 스터디 그룹 데이터 없을 경우 레이블 표시
- [x] navigation title, item 설정
- [x] Action Sheet 생성 후 + 버튼과 연결

## 참고한 코드 출처
- []()

**Comment by wonhui-kim** [comment]
문제) table custom cell의 padding, 셀간 spacing 주기에서 헤매는 중입니다

**Comment by wonhui-kim** [comment]
셀 크기, 간격 문제 -> 셀 내부 contentView inset으로 해결 완료

**Comment by Lia316** [comment]
> 셀 크기, 간격 문제 -> 셀 내부 contentView inset으로 해결 완료

오~ 구체적으로 어떻게 해결하셨는지 [FIX] 이슈 하나 파도 좋을 것 같아요!
