### ISSUE TITLE
[FEAT] StudyRoomView 차트 구현

### ISSUE THREAD

**Issue by unuhqueen** [DeveloperAcademy-POSTECH/MC3-Team1-Hatnya#23]
## 💡 Issue
- StudyRoomView의 차트를 구현한다.

## 📝  todo
- [x] 샘플 데이터 및 데이터 구조 만들기
- [ ] 차트 형태 구현
- [ ] 샘플 데이터와 차트 색칠 여부 연결
