### ISSUE TITLE
[FEAT] ChartView 구현

### ISSUE THREAD

**Issue by MMMIIIN** [DeveloperAcademy-POSTECH/MC3-Team1-Hatnya#30]
## 💡 Issue

- StackView를 이용한 막대 Chart를 구현합니다

## 📝  todo
- [x] 막대 차트 구현
- [x] 인원 수 대로 차트 표시
- [ ] 숙제 추가 시 차트 개수 추가

## 참고한 코드 출처
- []()
