### ISSUE TITLE
[FEAT] 뷰컨트롤러 연결

### ISSUE THREAD

**Issue by kelly1422** [DeveloperAcademy-POSTECH/MC3-Team1-Hatnya#34]
## 💡 Issue
기능에 따라 뷰컨트롤러들을 연결

## 📝  todo
- [ ] 시작 화면 설정
- [ ] 다음 버튼, 닉네임 뷰컨 연결
- [ ] 스터디 리스트 누르면 스터디룸뷰컨으로 연결
- [ ] 액션시트 각각 코드입력, 방생성으로 연결
- [ ] 백버튼 연결

## 참고한 코드 출처
