### ISSUE TITLE
[FEAT] UUID에 따라 StudyListView 다르게 띄우기

### ISSUE THREAD

**Issue by unuhqueen** [DeveloperAcademy-POSTECH/MC3-Team1-Hatnya#38]
## 💡 Issue

UUID를 사용자의 UID로 설정한 후, 해당 사용자가 가입된 스터디그룹의 리스트만 띄우는 기능

## 📝  todo
- [ ] 기기 uuid를 6글자로 컷해서 사용자의 uid로 업로드하기
- [ ] 사용자의 uid가 포함된 리스트 데이터 받아오기
- [ ] 받아온 데이터를 샘플 데이터 대신 연결하기
