### ISSUE TITLE
[FEAT]: JoinStudyView 에서 입력한 코드로 스터디 검색하기

### ISSUE THREAD

**Issue by wonhui-kim** [DeveloperAcademy-POSTECH/MC3-Team1-Hatnya#55]
## 💡 Issue
JoinStudyView에서 스터디 코드 입력 시 해당 코드를 가진 스터디를 보여주고, 없으면 없다는 label 띄우기

## 📝  todo
- [x] firebase의 StudyGroup data 가져오기
- [x] 입력한 코드를 가진 스터디 정보 보여주기
- [x] 입력한 코드를 가진 스터디가 없으면 없다는 label 띄우기

## 참고한 코드 출처
- [Firebase 공식 DocC](https://firebase.google.com/docs/database/ios/read-and-write?hl=ko)
